### ISSUE TITLE
Show the current time

### ISSUE THREAD

**Issue by moham96** [BiglySoftware/BiglyBT-plugin-SpeedScheduler#2]
Hi,
I've been having issues lately where the downloads are stopped at the wrong time, I have the following rules:

> daily pause_all from 08:00 to 01:00
> daily resume_all from 01:00 to 08:00

but for some reason the torrents are getting paused at around 06:00 so I need to know what does the current time that biglybt is getting from the system to pinpoint the problem, maybe there is somewhere in biglybt that shows the current time and date but I haven't found it.

Regards

**Comment by parg** [comment]
I've added a line to the info displayed when you do 

Tools->Speed Limit->View Current...

to show the scheduler's current view of the time:

![image](https://user-images.githubusercontent.com/395293/53975470-d02c2100-40fc-11e9-8cc4-04f38a52e374.png)

Please check the next beta (B27)

**Comment by moham96** [comment]
@parg Thanks.
