### ISSUE TITLE
pause not working on multi tag torrents

### ISSUE THREAD

**Issue by Xyrio** [BiglySoftware/BiglyBT-plugin-SpeedScheduler#3]
pausing seeding torrents for a certain tag enabled but does not work when torrent has multiple tags. when only the configured tag exists on torrent it does correctly "stopped (speed scheduler)".

the speed limits are applied correctly.

fyi:
the text based way of speed limiting stops correctly: https://github.com/BiglySoftware/BiglyBT/wiki/Speed-Limit-Scheduler
enable=yes
daily def from 00:00 to 00:00 start_tag:u
daily def from 12:00 to 12:30 stop_tag:u

plugin version 1.7.8
Java 1.8.0_181 (64 bit)  Oracle Corporation
SWT v4942r22, win32, zoom=100, dpi=96
Windows 7 v6.1, amd64 (64 bit)
B2.7.0.3_B28/4 az3

**Comment by parg** [comment]
Try 1.7.9 - not tested so please give feedback.

**Comment by Xyrio** [comment]
works.
