### ISSUE TITLE
configurable pause or stop

### ISSUE THREAD

**Issue by Xyrio** [BiglySoftware/BiglyBT-plugin-SpeedScheduler#4]
gui saies pause but it actually stops torrents.

better having an option to choose either.

pause should at least remember if torrent was forced or normally running especially for seeding torrents. torrents that need to be stopped can be worked around by not using tag with applied speeds limits.

reason is that pause should remember the state it had before, so when starting again it should restore the previous status like forced seeding, normal seeding, stopped and also normally paused

fyi:
the internal scheduler has pause_tag on wich start_tag does not work and one has to use resume_tag but that does not remember previous state either, unlike when normal manual pause.

**Comment by parg** [comment]
If only we had someone to maintain that plugin...

No idea why it uses 'stop', as you say, documentation says 'pause'.

**Comment by parg** [comment]
Try 1.7.9 - not tested so please give feedback.

**Comment by Xyrio** [comment]
it does pause now but only when not forced seeding.
it should pause forced too and resume correctly back to forced.

**Comment by parg** [comment]
I disagree - when something is in a forced state nothing automatic acts on it

**Comment by Xyrio** [comment]
well if forced is ment to ignore any other rules then it fits and remembering state with resume is unnecessary because it can only go into queued.

**Comment by parg** [comment]
Version 1.8 has a config option to enable pausing of force-started downloads, tell me if it works

**Comment by Xyrio** [comment]
works thanks
